version: "3"
services:
  hello:
    image: hello-server:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - sm_net
  time:
    image: time-server:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - sm_net

networks:
  sm_net:
